# Generated by Django 6.0 on 2025-12-29 15:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoria de Peça',
                'verbose_name_plural': 'Categorias de Peças',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(editable=False, help_text='Gerado automaticamente', max_length=50, unique=True, verbose_name='Código Interno')),
                ('part_number', models.CharField(blank=True, help_text='Código do fabricante/fornecedor', max_length=100, null=True, verbose_name='Part Number')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Peça')),
                ('descricao', models.TextField(blank=True, help_text='Descrição completa da peça, especificações técnicas, etc.', null=True, verbose_name='Descrição Detalhada')),
                ('quantidade_minima', models.IntegerField(default=1, help_text='Quantidade mínima que gera alerta de compra', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade Mínima')),
                ('localizacao', models.CharField(blank=True, help_text='Ex: Prateleira A1, Gaveta 3', max_length=100, null=True, verbose_name='Localização no Estoque')),
                ('ultimo_preco_compra', models.DecimalField(decimal_places=2, default=0.0, help_text='Atualizado automaticamente na entrada de notas fiscais', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Último Preço de Compra')),
                ('margem_lucro', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentual de lucro (ex: 30.00 para 30%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Margem de Lucro (%)')),
                ('preco_venda', models.DecimalField(decimal_places=2, default=0.0, editable=False, help_text='Calculado automaticamente: Preço Compra + Margem', max_digits=10, verbose_name='Preço de Venda')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Peça',
                'verbose_name_plural': 'Peças',
                'ordering': ['codigo_interno'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('ajuste', 'Ajuste')], max_length=10)),
                ('quantidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('valor_unitario', models.DecimalField(decimal_places=2, help_text='Valor unitário nesta movimentação', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Unitário')),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fornecedores.fornecedor')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-data_movimentacao'],
            },
        ),
    ]
