# Generated by Django 6.0 on 2025-12-29 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
        ('financeiro', '0001_initial'),
        ('fornecedores', '0001_initial'),
        ('ordem_servico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='nota_fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_estoque', to='financeiro.notafiscal', verbose_name='Nota Fiscal'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='ordem_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_estoque', to='ordem_servico.ordemservico'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='peca',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pecas', to='estoque.categoriapeca'),
        ),
        migrations.AddField(
            model_name='peca',
            name='fornecedor_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pecas_fornecidas', to='fornecedores.fornecedor', verbose_name='Fornecedor Principal'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='peca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='estoque.peca'),
        ),
        migrations.AddIndex(
            model_name='peca',
            index=models.Index(fields=['codigo_interno'], name='estoque_pec_codigo__fc4014_idx'),
        ),
        migrations.AddIndex(
            model_name='peca',
            index=models.Index(fields=['part_number'], name='estoque_pec_part_nu_e00bc7_idx'),
        ),
    ]
