# Generated by Django 6.0 on 2025-12-29 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_initial'),
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peca',
            options={'ordering': ['nome'], 'verbose_name': 'Peça', 'verbose_name_plural': 'Peças'},
        ),
        migrations.RemoveIndex(
            model_name='peca',
            name='estoque_pec_codigo__fc4014_idx',
        ),
        migrations.RemoveIndex(
            model_name='peca',
            name='estoque_pec_part_nu_e00bc7_idx',
        ),
        migrations.AlterField(
            model_name='peca',
            name='codigo_interno',
            field=models.CharField(editable=False, max_length=50, unique=True, verbose_name='Código Interno'),
        ),
        migrations.AlterField(
            model_name='peca',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='peca',
            name='fornecedor_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fornecedores.fornecedor'),
        ),
        migrations.AlterField(
            model_name='peca',
            name='localizacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='peca',
            name='margem_lucro',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Margem de Lucro (%)'),
        ),
        migrations.AlterField(
            model_name='peca',
            name='part_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Part Number'),
        ),
        migrations.AlterField(
            model_name='peca',
            name='preco_venda',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço de Venda'),
        ),
        migrations.AlterField(
            model_name='peca',
            name='quantidade_minima',
            field=models.IntegerField(default=5, verbose_name='Quantidade Mínima'),
        ),
        migrations.AlterField(
            model_name='peca',
            name='ultimo_preco_compra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Último Preço de Compra'),
        ),
        migrations.RemoveField(
            model_name='peca',
            name='data_atualizacao',
        ),
    ]
