# Generated by Django 5.0 on 2025-12-13 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('estoque', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_os', models.CharField(max_length=20, unique=True, verbose_name='Número da OS')),
                ('tipo_equipamento', models.CharField(choices=[('tv', 'TV'), ('notebook', 'Notebook'), ('desktop', 'Computador Desktop'), ('monitor', 'Monitor'), ('impressora', 'Impressora'), ('outro', 'Outro')], max_length=20)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Série')),
                ('defeito_relatado', models.TextField(verbose_name='Defeito Relatado pelo Cliente')),
                ('defeito_encontrado', models.TextField(blank=True, null=True, verbose_name='Defeito Encontrado')),
                ('status', models.CharField(choices=[('recepcao', 'Recepção'), ('avaliacao', 'Em Avaliação'), ('aguardando_aprovacao', 'Aguardando Aprovação'), ('aprovado', 'Aprovado'), ('em_reparo', 'Em Reparo'), ('concluido', 'Concluído'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='recepcao', max_length=30)),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('data_avaliacao', models.DateTimeField(blank=True, null=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('prazo_estimado', models.DateField(blank=True, null=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('data_entrega', models.DateTimeField(blank=True, null=True)),
                ('valor_mao_obra', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Mão de Obra')),
                ('valor_pecas', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor das Peças')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dias_garantia', models.IntegerField(default=90, verbose_name='Dias de Garantia')),
                ('data_fim_garantia', models.DateField(blank=True, null=True)),
                ('observacoes_internas', models.TextField(blank=True, null=True, verbose_name='Observações Internas')),
                ('observacoes_cliente', models.TextField(blank=True, null=True, verbose_name='Observações para o Cliente')),
                ('atendente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='os_atendidas', to=settings.AUTH_USER_MODEL, verbose_name='Atendente Responsável')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='clientes.cliente')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='os_tecnico', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Responsável')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ['-data_entrada'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(max_length=30)),
                ('status_novo', models.CharField(max_length=30)),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='ordem_servico.ordemservico')),
            ],
            options={
                'verbose_name': 'Histórico da OS',
                'verbose_name_plural': 'Históricos das OS',
                'ordering': ['-data_alteracao'],
            },
        ),
        migrations.CreateModel(
            name='PecaUtilizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas_utilizadas', to='ordem_servico.ordemservico')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.peca')),
            ],
            options={
                'verbose_name': 'Peça Utilizada',
                'verbose_name_plural': 'Peças Utilizadas',
            },
        ),
    ]
