# Generated by Django 6.0 on 2025-12-29 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('ordem_servico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('foto_entrada', 'Foto na Entrada'), ('foto_defeito', 'Foto do Defeito'), ('foto_reparo', 'Foto do Reparo'), ('foto_entrega', 'Foto na Entrega'), ('documento', 'Documento'), ('outro', 'Outro')], max_length=20)),
                ('arquivo', models.FileField(upload_to='os_anexos/%Y/%m/')),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Anexo da OS',
                'verbose_name_plural': 'Anexos das OS',
                'ordering': ['-data_upload'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possui_arranhoes', models.BooleanField(default=False, verbose_name='Possui arranhões')),
                ('possui_amassados', models.BooleanField(default=False, verbose_name='Possui amassados')),
                ('possui_quebras', models.BooleanField(default=False, verbose_name='Possui quebras')),
                ('possui_oxidacao', models.BooleanField(default=False, verbose_name='Possui oxidação')),
                ('liga_normalmente', models.BooleanField(default=True, verbose_name='Liga normalmente')),
                ('tem_senha', models.BooleanField(default=False, verbose_name='Equipamento tem senha')),
                ('senha_fornecida', models.BooleanField(default=False, verbose_name='Senha foi fornecida')),
                ('possui_bateria', models.BooleanField(default=True, verbose_name='Possui bateria')),
                ('possui_carregador', models.BooleanField(default=False, verbose_name='Possui carregador')),
                ('possui_cabo', models.BooleanField(default=False, verbose_name='Possui cabo')),
                ('possui_case', models.BooleanField(default=False, verbose_name='Possui case/capa')),
                ('observacoes_checklist', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Checklist da OS',
                'verbose_name_plural': 'Checklists das OS',
            },
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='avaliacao_cliente',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='cliente_notificado_conclusao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='cliente_notificado_entrada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='cliente_notificado_orcamento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='comentario_avaliacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='solucao_aplicada',
            field=models.TextField(blank=True, null=True, verbose_name='Solução Aplicada'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='ultima_notificacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='tipo_equipamento',
            field=models.CharField(choices=[('tv', 'TV'), ('notebook', 'Notebook'), ('desktop', 'Computador Desktop'), ('monitor', 'Monitor'), ('impressora', 'Impressora'), ('celular', 'Celular/Smartphone'), ('tablet', 'Tablet'), ('outro', 'Outro')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='ordemservico',
            index=models.Index(fields=['status', 'data_entrada'], name='ordem_servi_status_0e5bfa_idx'),
        ),
        migrations.AddIndex(
            model_name='ordemservico',
            index=models.Index(fields=['cliente', 'status'], name='ordem_servi_cliente_a4c2bb_idx'),
        ),
        migrations.AddIndex(
            model_name='ordemservico',
            index=models.Index(fields=['prazo_estimado'], name='ordem_servi_prazo_e_448097_idx'),
        ),
        migrations.AddField(
            model_name='anexoos',
            name='ordem_servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='ordem_servico.ordemservico'),
        ),
        migrations.AddField(
            model_name='anexoos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklistos',
            name='ordem_servico',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='ordem_servico.ordemservico'),
        ),
    ]
