# Generated by Django 6.0 on 2025-12-29 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('estoque', '0003_alter_peca_options_and_more'),
        ('ordem_servico', '0002_anexoos_checklistos_ordemservico_avaliacao_cliente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='os_fotos/%Y/%m/')),
                ('descricao', models.CharField(blank=True, help_text='Ex: Arranhão na tampa, Tela quebrada', max_length=100)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoStatusOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, choices=[('recepcao', '1. Recepção'), ('analise', '2. Em Análise'), ('aprovacao', '3. Aguardando Aprovação'), ('reparo', '4. Em Reparo'), ('pronto', '5. Pronto'), ('entregue', '6. Entregue'), ('cancelado', '7. Cancelado')], max_length=20, null=True)),
                ('novo_status', models.CharField(choices=[('recepcao', '1. Recepção'), ('analise', '2. Em Análise'), ('aprovacao', '3. Aguardando Aprovação'), ('reparo', '4. Em Reparo'), ('pronto', '5. Pronto'), ('entregue', '6. Entregue'), ('cancelado', '7. Cancelado')], max_length=20)),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-data_alteracao'],
            },
        ),
        migrations.CreateModel(
            name='PecaUtilizadaOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário (Venda)')),
                ('valor_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
            ],
            options={
                'verbose_name': 'Peça Utilizada',
                'verbose_name_plural': 'Peças Utilizadas',
            },
        ),
        migrations.RemoveField(
            model_name='anexoos',
            name='ordem_servico',
        ),
        migrations.RemoveField(
            model_name='anexoos',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='checklistos',
            name='ordem_servico',
        ),
        migrations.RemoveField(
            model_name='historicoos',
            name='ordem_servico',
        ),
        migrations.RemoveField(
            model_name='historicoos',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='pecautilizada',
            name='ordem_servico',
        ),
        migrations.RemoveField(
            model_name='pecautilizada',
            name='peca',
        ),
        migrations.RemoveIndex(
            model_name='ordemservico',
            name='ordem_servi_status_0e5bfa_idx',
        ),
        migrations.RemoveIndex(
            model_name='ordemservico',
            name='ordem_servi_cliente_a4c2bb_idx',
        ),
        migrations.RemoveIndex(
            model_name='ordemservico',
            name='ordem_servi_prazo_e_448097_idx',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='data_previsao',
            field=models.DateField(blank=True, null=True, verbose_name='Previsão de Entrega'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='defeito_cliente',
            field=models.TextField(default='Não informado', help_text='Descrição do problema segundo o cliente', verbose_name='Defeito relatado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='diagnostico_tecnico',
            field=models.TextField(blank=True, null=True, verbose_name='Diagnóstico Técnico'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='garantia_dias',
            field=models.IntegerField(default=90, verbose_name='Garantia (dias)'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='valor_mao_de_obra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='atendente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='os_atendidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='marca',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='modelo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='observacoes_cliente',
            field=models.TextField(blank=True, help_text='Observações que saem na impressão', null=True),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='observacoes_internas',
            field=models.TextField(blank=True, help_text='Visível apenas para a equipe', null=True),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('recepcao', '1. Recepção'), ('analise', '2. Em Análise'), ('aprovacao', '3. Aguardando Aprovação'), ('reparo', '4. Em Reparo'), ('pronto', '5. Pronto'), ('entregue', '6. Entregue'), ('cancelado', '7. Cancelado')], default='recepcao', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_tecnico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='tipo_equipamento',
            field=models.CharField(help_text='Ex: TV, Notebook, Celular', max_length=50),
        ),
        migrations.AddField(
            model_name='fotoos',
            name='os',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='ordem_servico.ordemservico'),
        ),
        migrations.AddField(
            model_name='historicostatusos',
            name='os',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='ordem_servico.ordemservico'),
        ),
        migrations.AddField(
            model_name='historicostatusos',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pecautilizadaos',
            name='os',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas', to='ordem_servico.ordemservico'),
        ),
        migrations.AddField(
            model_name='pecautilizadaos',
            name='peca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.peca'),
        ),
        migrations.DeleteModel(
            name='AnexoOS',
        ),
        migrations.DeleteModel(
            name='ChecklistOS',
        ),
        migrations.DeleteModel(
            name='HistoricoOS',
        ),
        migrations.DeleteModel(
            name='PecaUtilizada',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='avaliacao_cliente',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='cliente_notificado_conclusao',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='cliente_notificado_entrada',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='cliente_notificado_orcamento',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='comentario_avaliacao',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='data_aprovacao',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='data_avaliacao',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='data_entrega',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='data_fim_garantia',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='defeito_encontrado',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='defeito_relatado',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='dias_garantia',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='numero_os',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='prazo_estimado',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='solucao_aplicada',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='ultima_notificacao',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='valor_mao_obra',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='valor_pecas',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='valor_total',
        ),
    ]
